/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sbqtr;

import com.google.cloud.bigquery.Field;
import com.google.cloud.bigquery.FieldList;

import java.util.List;

public class SFieldList {
    final List<Field> fields;

    public SFieldList(List<Field> fields) {
        this.fields = fields;
    }

    public FieldList toFieldList() {
        return com.google.cloud.bigquery.FieldList.of(fields);
    }
}
